### ISSUE TITLE
Can't find table (Windows)

### ISSUE THREAD

**Issue by mikesievert** [jrey999/mlb-positive-ev#2]
Work@DESKTOP-EE5E42Q MINGW64 ~/Desktop/mlb-positive-ev (main)
$ python odds.py
Traceback (most recent call last):
  File "C:\Users\Work\Desktop\mlb-positive-ev\odds.py", line 10, in <module>
    cursor.execute(
sqlite3.OperationalError: no such table: game

Hi i get the following error.

in VS Code the error looks like this

PS C:\Users\Work> & C:/Users/Work/AppData/Local/Programs/Python/Python310/python.exe c:/Users/Work/Desktop/mlb-positive-ev/odds.py
Traceback (most recent call last):
  File "c:\Users\Work\Desktop\mlb-positive-ev\odds.py", line 5, in <module>
    data, cursor = get_markets(), DB.cursor()
  File "c:\Users\Work\Desktop\mlb-positive-ev\odds\funcs.py", line 13, in get_markets
    json.dump(data, open("meta/sampledata/data.json", "w"), indent=0)
FileNotFoundError: [Errno 2] No such file or directory: 'meta/sampledata/data.json'
PS C:\Users\Work> 

Have you ran into this before? If so, any help here would be much appreciated. Working off a Macbook M1.
Thanks.

**Comment by jrey999** [comment]
So the error
 ```
python odds.py
Traceback (most recent call last):
File "C:\Users\Work\Desktop\mlb-positive-ev\odds.py", line 10, in
cursor.execute(
sqlite3.OperationalError: no such table: game
```
suggests that the tables have not been created yet.
Make sure you've ran,
`./shell/schema.sh`
and that it tells you that the tables were just created.
Let me know if that doesn't work.
